#%RAML 1.0 DataType

type: object
properties:
  toNumber:
    type: string
    required: true
    example: "+14158557316"
  fromNumber:
    type: string
    required: true
    example: "+918298082521"

